default_context:
  project_name: '{{ cookiecutter.project_name }}'
  project_slug: '{{ cookiecutter.project_slug }}'
  domain_main: '{{ cookiecutter.domain_main }}'
  domain_staging: '{{ cookiecutter.domain_staging }}'
  secret_key: '{{ cookiecutter.secret_key }}'
  env_prefix: "{{cookiecutter.project_slug|replace('-', '_')|upper}}_",
  postgres_password: '{{ cookiecutter.postgres_password }}'

  docker_image_prefix: '{{ cookiecutter.docker_image_prefix }}'
  docker_image_service: '{{ cookiecutter.docker_image_prefix }}{{cookiecutter.project_slug}}'
  service_port: '{{ cookiecutter.service_port }}'
  _copy_without_render: [ "**/chart/templates/**/*",
                          "**/chart/templates/*"
  ]
  _template: ./
