{{- if .Values.db.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: dbsecrets
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.db.url }}
  {{ .Values.envPrefix }}SQLALCHEMY_DATABASE_URI: {{ .Values.db.url }}
  {{ else }}
  {{ .Values.envPrefix }}POSTGRES_SERVER: {{ .Values.db.host }}
  {{ .Values.envPrefix }}POSTGRES_USER: {{ .Values.db.username }}
  {{ .Values.envPrefix }}POSTGRES_PASSWORD: {{ .Values.db.password }}
  {{ .Values.envPrefix }}POSTGRES_DB: {{ .Values.db.db }}
  {{ end }}
{{ end }}